sudo: required
services:
  - docker

before_install:
  - docker build -t akihr/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true akihr/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-931234710300"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY